### ISSUE TITLE
FIle not found error

### ISSUE THREAD

**Issue by chalukyareddy** [jitcoder/lora-info#7]
File not found: /workspace/ComfyUI/custom_nodes/lora-info/db.json
Error handling request
Traceback (most recent call last):
  File "/workspace/venv/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "/workspace/venv/lib/python3.10/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
  File "/workspace/venv/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/workspace/ComfyUI/server.py", line 47, in cache_control
    response: web.Response = await handler(request)
  File "/workspace/ComfyUI/custom_nodes/lora-info/lora_info.py", line 112, in fetch_lora_info
    (output, triggerWords, examplePrompt, baseModel) = get_lora_info(lora_name)
  File "/workspace/ComfyUI/custom_nodes/lora-info/lora_info.py", line 68, in get_lora_info
    LORAsha256 = calculate_sha256(lora_path)
  File "/workspace/ComfyUI/custom_nodes/lora-info/lora_info.py", line 43, in calculate_sha256
    with open(file_path, "rb") as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by jitcoder** [comment]
Hello, I believe this issue was resolved a while ago and I forgot to close the ticket. if the issue is still present please feel free to reopen the issue
